### ISSUE TITLE
Webvr isnt working

### ISSUE THREAD

**Issue by nirba27** [alx/parasol#14]
Hey ,

i tried to load the webvr mode in the index.html 
but nothing seems to change the mode
what am i doing wrong ?

this is my code: 
![capture](https://user-images.githubusercontent.com/37560691/37627784-c60e00f0-2bde-11e8-96ab-49c0d9f1f168.PNG)

**Comment by alx** [comment]
Hi @nirba27 

thanks for your feedback.

* do you have any error displayed in the console ?
* do you have the latest version of http://parasol.alexgirard.com/assets/js/parasol.js ?

Have a nice day,

Alex

**Comment by nirba27** [comment]
Hi Alex,
updating the file seems to resolve the problem , Thank you very much.
It is possible to enable the components like               
                {"name": "SearchInput"},
                {"name": "SelectedNode"}
In the VR mode ?

**Comment by alx** [comment]
Great :)

No, default components are not available in vr mode, there is probably ways to add them, but I havn't spend time on it yet. I'd be glad to accept PR if you succeed integrating this feature.
