### ISSUE TITLE
How to map search field to query parameter ?

### ISSUE THREAD

**Issue by acabrol** [alx/parasol#18]

**Comment by alx** [comment]
To setup the datasource:

https://github.com/alx/parasol/blob/master/src/Components/Filters/SearchInput.js#L14

It's filtering on the `text` attribute returned from the `network.get("graph").nodes.map`, so you can change this value to modify the query parameter.

At the moment, it's only using `node.id`, or `node.metadata.label` if available.

and

https://github.com/alx/parasol/blob/master/src/Components/Filters/SearchInput.js#L79
