### ISSUE TITLE
Edge weight filtering doesn't work

### ISSUE THREAD

**Issue by beniz** [alx/parasol#9]
For very fast filtering, it'd be useful to:
- maintain a list of edges ordered from highest to lowest weight
- use the filtering value to look up the ordering and remove the upper, middle or lower part.

**Comment by alx** [comment]
Look for "binary search tree" to use during filtering.

**Comment by alx** [comment]
Solved in latest version, update parasol.js with version available at http://parasol.alexgirard.com/assets/js/parasol.js

![component_edge_weight](https://user-images.githubusercontent.com/373/32940615-6e6efd1a-cb83-11e7-9ad5-0aad7e53ebe1.png)
